spring.application.name=On-Time Health DB

# 1. Direcci�n a tu base de datos (Cambi� 'tu_base_de_datos' por 'mydb')
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mydb

# 2. Tu usuario de pgAdmin (Cambi� 'postgres' por 'myuser')
spring.datasource.username=myuser

# 3. Tu contrase�a real de pgAdmin (Cambi� 'mypassword' por tu contrase�a secreta)
spring.datasource.password=mypassword

spring.datasource.driver-class-name=org.postgresql.Driver

# Esto hace que Spring cree las tablas autom�ticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com